### ISSUE TITLE
Tag is missing for v1.88

### ISSUE THREAD

**Issue by mattrbeck** [oprypin/crystal-imgui#10]
Figured this was just forgotten since most other versions are tagged :)

**Comment by mattrbeck** [comment]
Looks like it's also missing on https://github.com/oprypin/crystal-imgui-sfml, fyi

**Comment by oprypin** [comment]
Yeah that's kinda intentional. I never figured out any approach for adding a tag and then still being able to make improvements to the code, so I always tag very late.

**Comment by mattrbeck** [comment]
You can force push tags to update which commit they're on, although I don't know how that plays with people pulling the repo over existing changes

My approach is just tag the update, and any further improvements Will be in the next version. ImGui tags new versions regularly enough that I don't worry about it

**Comment by joshrickard** [comment]
First off, thanks for taking the time to build and maintain your Crystal libraries.

I happened to stumble on this issue after getting method missing errors while trying to use the block form on various UI elements e.g.

```crystal
ImGui.tab_bar("tabs") do
end

# vs

ImGui.begin_tab_bar("tabs")
ImGui.end_tab_bar
```

If anyone else happens to land on this issue and wants to use the block form before the next tag, this worked for me:

```yaml
dependencies:
  imgui:
    github: oprypin/crystal-imgui
    commit: 33f209fd40de2799734562e6f58cdb3c7909b73c
```

**Comment by oprypin** [comment]
Uh sorry. This is tagged now.
