### ISSUE TITLE
No access to  `ClearActiveID()`

### ISSUE THREAD

**Issue by wolfgang371** [oprypin/crystal-imgui#4]
Hi Oleg,
is there a way to access the (internal) `ClearActiveID()` (it seems to be part of `cimgui.h`, though)? This seems to be necessary to have more control over `input_text` (see https://github.com/ocornut/imgui/issues/3290).
Thanks!

**Comment by oprypin** [comment]
No, exposing imgui_internal.h is not currently a goal.
https://github.com/ocornut/imgui/blob/3776ba565f91be00dfe12c9fd99223c2310b37c5/imgui_internal.h#L2259

**Comment by wolfgang371** [comment]
so we should try to make it public then?

**Comment by oprypin** [comment]
I don't know honestly. People mentioned several times that it's ok to use internal. I'm just not an experienced user of imgui. My main reason to not expose internal is that it's much more difficult. I may just reconsider. Collaborating with an experienced user would help.

---
This certainly seems like a function that shouldn't be internal. But so do many other functions there. You can try to inquire, but using this issue as a reference would not be a strong move probably.

**Comment by wolfgang371** [comment]
FYI: I have a discussion on this now on https://github.com/ocornut/imgui/issues/3878

**Comment by oprypin** [comment]
Well that went exactly as I imagined

**Comment by oprypin** [comment]
Now you can call `LibImGui.ClearActiveID()` and, similarly, other internal funcs.

The internal funcs will not be in `ImGui` module, nor in documentation.

[See the commit](https://github.com/oprypin/crystal-imgui/commit/d33abbf1ec3994226304ffb0be7eef330574fd79#diff-9e694350424447194fafb32eba632db8e82b400cb3b8a19140221996ae28b3d4) for what this adds.

---

If you find this insufficient, please do continue the conversation.

**Comment by wolfgang371** [comment]
Thanks, works for me!
Maybe Omar will still make it superfluous in this use case (IMHO more elegant).

**Comment by ocornut** [comment]
To clarify we do indeed intend to provide a public-facing solution for https://github.com/ocornut/imgui/issues/3878

I just don't think exposing `ClearActiveID()` is the right solution especially as it only provide a clunky workaround for this specific problem.

As for exposing imgui_internal.h in whichever languages/bindings:
- One possible pragmatic answer IHMO is to selectively expose internal functions/symbols only when requested/needed for a fix/workaround. Keep some friction in and decrease need for maintenance.
