### ISSUE TITLE
Feature request: Add methods that accept a block and do pushes/pops for you

### ISSUE THREAD

**Issue by mattrbeck** [oprypin/crystal-imgui#8]
In a couple projects, I've found myself adding methods like
```crystal
def with_style_color(idx : ImGui::ImGuiCol, col : ImGui::ImVec4, &) : Nil
  ImGui.push_style_color(idx, col)
  yield
  ImGui.pop_style_color
end

def child(str_id : String, size : ImGui::ImVec2 = ImGui::ImVec2.new(0, 0), border : Bool = false, flags : ImGui::ImGuiWindowFlags = ImGui::ImGuiWindowFlags.new(0), &) : Nil
  yield if ImGui.begin_child(str_id, size, border, flags)
  ImGui.end_child
end
```

I think it'd be nice if this shard supported those. I'm happy to add them manually if you like, or if you want to update the generator that'd be awesome. The complication there is that ImGui isn't consistent regarding when `end` methods should be called. For example, you always have to call `end_child` after `begin_child`, but you only call `end_menu` if `begin_menu` returns true. What do you think?

**Comment by oprypin** [comment]
Overall, I think it's a great idea.
Without looking into it, manual additions seem to be the way to go. But I will look into it ~now.
Also I'm kinda wary because these will have no presence in _demo  (so they can just break unnoticed)

**Comment by oprypin** [comment]
> ImGui isn't consistent regarding when end methods should be called. For example, you always have to call end_child after begin_child, but you only call end_menu if begin_menu returns true. 

Could you make some kind of snippet with a complete list of possible functions and conventions?

**Comment by mattrbeck** [comment]
Definitely, I can do that this evening

**Comment by oprypin** [comment]
Hm seems I'm getting quite good mileage out of first changing `src/demo.cr` and seeing what it requires. Maybe the complete list will fill the gaps, but maybe it's not necessary.

**Comment by oprypin** [comment]
Ah this is a pity
```
 > 26 |   def with_style_var(*args, **kwargs)
 > 27 |     
 > 28 |     if push_style_var(*args, **kwargs)
               ^-------------
Error: no overload matches 'ImGui.push_style_var' with types ImGui::ImGuiStyleVar, Int32

Overloads are:
 - ImGui.push_style_var(idx : ImGuiStyleVar, val : Float32)
 - ImGui.push_style_var(idx : ImGuiStyleVar, val : ImVec2)
```

**Comment by oprypin** [comment]
Anyway this is what I have for demos so far.

https://github.com/oprypin/crystal-imgui/compare/within?expand=1&w=1

**Comment by mattrbeck** [comment]
> Ah this is a pity

Ah yeah, I experienced the same thing :/

Regarding the possible conventions, I put this together. I haven't yet had a chance to double-check it, but I think this should cover it

Open | Close | Conditional?
-- | -- | --
PushAllowKeyboardFocus | PopAllowKeyboardFocus | No
PushButtonRepeat | PopButtonRepeat | No
PushClipRect | PopClipRect | No
PushClipRectFullScreen | PopClipRect | No
PushFont | PopFont | No
PushID | PopID | No
PushItemWidth | PopItemWidth | No
PushStyleColor | PopStyleColor | No
PushStyleVar | PopStyleVar | No
PushTextureID | PopTextureID | No
PushTextWrapPos | PopTextWrapPos | No
Begin | End | No
BeginChild | EndChild | No
BeginChildFrame | EndChildFrame | No
BeginCombo | EndCombo | Yes
BeginDisabled | EndDisabled | No
BeginDragDropSource | EndDragDropSource | Yes
BeginDragDropTarget | EndDragDropTarget | Yes
BeginGroup | EndGroup | No
BeginListBox | EndListBox | Yes
BeginMainMenuBar | EndMainMenuBar | Yes
BeginMenu | EndMenu | Yes
BeginMenuBar | EndMenuBar | Yes
BeginPopup | EndPopup | Yes
BeginPopupContextItem | EndPopup | Yes
BeginPopupContextVoid | EndPopup | Yes
BeginPopupContextWindow | EndPopup | Yes
BeginPopupModal | EndPopup | Yes
BeginTabBar | EndTabBar | Yes
BeginTabItem | EndTabItem | Yes
BeginTable | EndTable | Yes
BeginTooltip | EndTooltip | No

**Comment by mattrbeck** [comment]
I see I listed them in the cpp source naming convention rather than the crystal naming convention. Lmk if you'd like me to translate those

**Comment by oprypin** [comment]
Nice, thanks!

**Comment by oprypin** [comment]
There is also TreeNode TreePop and stuff, what's up with those?

**Comment by mattrbeck** [comment]
Ah, I guess I should have searched more broadly. I only filtered on functions beginning with push/pop and begin/end since searching more generally was pretty noisy. I missed the tree functions as a result

**Comment by oprypin** [comment]
And also these 3 are special

* [Begin](https://github.com/ocornut/imgui/blob/9aae45eb4a05a5a1f96be1ef37eb503a12ceb889/imgui.h#L321)
* [BeginChild](https://github.com/ocornut/imgui/blob/9aae45eb4a05a5a1f96be1ef37eb503a12ceb889/imgui.h#L333)
* [BeginChildFrame](https://github.com/ocornut/imgui/blob/9aae45eb4a05a5a1f96be1ef37eb503a12ceb889/imgui.h#L863)

[I got them handled](https://github.com/oprypin/crystal-imgui/pull/9/files?w=1#diff-5774d9a1486dad3e31095f0a4efbf5d2b7945b73056959fe5c618c63a119af57)
